#!/bin/bash
#PBS -k o
#PBS -l nodes=1:ppn=4,walltime=00:10:00

[ $PBS_O_WORKDIR ] && cd $PBS_O_WORKDIR

#echo "setting miniconda path..."
#unset PYTHONPATH
#export PATH=/N/u/gberto/Karst/miniconda2/bin:$PATH
echo "setting path for sklearn 20..."
PYTHONPATH=/N/u/gberto/Karst/git/scikit-learn/:$PYTHONPATH
export PYTHONPATH

measures=`jq -r '.measures' config.json`

arr_meas=()
arr_meas+=(${measures})
num_ex=$((${#arr_meas[@]} - 2))

echo "$num_ex target subjects found."

mkdir csv_all;
for i in `seq 1 ${num_ex}`; 
do 
	measure=${arr_meas[i]//[,\"]}
	id_meas=$(jq -r "._inputs[$i-1].meta.subject" config.json | tr -d "_")
	cp ${measure} csv_all/${id_meas}_output_FiberStats.csv;
done

echo "Computing ROC curves"
mkdir images;
python plot_roc.py

if [ -z "$(ls -A -- "images")" ]; then    
	echo "Computation failed."
	exit 1
else    
	echo "Computation done."
fi
